// GENERATED by scripts/generate-registry.ts - do not edit by hand. `bun run registry` regenerates it.

import type { ModuleMeta } from "./types.js";

const at = (path: string): string => new URL(path, import.meta.url).href;

export const coreRegistry: ModuleMeta[] = [
  {
    meta: { name: "@ashstack/core" },
    url: at("../core/rules/core/index.js"),
    rules: {
      "no-comments": {},
      "no-naming-convention": {},
      "no-packed-condition": {},
      "use-design-system": { defaultOff: true },
      "components-tsx-only": { defaultOff: true },
      "hoist-intl": {},
    },
  },
  {
    meta: { name: "@ashstack/zod" },
    url: at("../core/rules/zod/index.js"),
    option: "zod",
    packages: ["zod"],
    rules: {
      "prefer-enum": {},
    },
  },
];

export const reactRegistry: ModuleMeta[] = [
  {
    meta: { name: "@ashstack/react" },
    url: at("../react/rules/react/index.js"),
    rules: {
      "no-unlabeled-icon-button": {},
      "no-svg-without-title": {},
    },
  },
  {
    meta: { name: "@ashstack/query" },
    url: at("../react/rules/query/index.js"),
    option: "query",
    packages: ["@tanstack/react-query"],
    rules: {
      "no-inline-keys": {},
      "no-deprecated-filters": {},
      "require-destructured-hooks": {},
      "no-fetch-in-query-fn": {},
      "next-page-param-undefined": {},
    },
  },
  {
    meta: { name: "@ashstack/zustand" },
    url: at("../react/rules/zustand/index.js"),
    option: "zustand",
    packages: ["zustand"],
    rules: {
      "require-selector": {},
    },
  },
  {
    meta: { name: "@ashstack/i18n" },
    url: at("../react/rules/i18n/index.js"),
    option: "i18n",
    packages: ["i18next", "react-i18next", "@lingui/core", "react-intl", "use-intl", "next-intl", "expo-localization"],
    rules: {
      "no-bare-text": {},
      "no-bare-attrs": {},
      "no-bare-toast": {},
    },
  },
  {
    meta: { name: "@ashstack/tailwind" },
    url: at("../react/rules/tailwind/index.js"),
    option: "tailwind",
    packages: ["tailwindcss"],
    rules: {
      "prefer-cn": {},
      "use-logical-classes": {},
    },
  },
  {
    meta: { name: "@ashstack/tanstack-router" },
    url: at("../react/rules/tanstack-router/index.js"),
    option: "tanstackRouter",
    packages: ["@tanstack/react-router"],
    rules: {
      "require-selector": {},
      "no-search-casts": {},
    },
  },
];

export const reactNativeRegistry: ModuleMeta[] = [
  {
    meta: { name: "@ashstack/react-native" },
    url: at("../react-native/rules/react-native/index.js"),
    restrictedImports: {
      paths: [
        {
          name: "react",
          importNames: ["forwardRef"],
          message:
            "Accept `ref` as a regular prop and delete the `forwardRef` wrapper — React 19 passes `ref` like any other prop.",
        },
        {
          name: "react",
          importNames: ["useContext"],
          message: "Call `use(Context)` instead of `useContext(Context)`; React 19 replaces the hook with it.",
        },
      ],
      patterns: [
        {
          group: ["expo-linear-gradient", "react-native-linear-gradient"],
          message:
            "Apply the gradient through the `experimental_backgroundImage` style property instead of a gradient component.",
        },
      ],
    },
    rules: {
      "no-keyboard-will-events": {},
      "no-scroll-position-state": {},
      "no-conditional-style-array": {},
      "no-leaked-render": {},
      "no-rn-image-network-source": {},
      "no-redundant-view-nesting": {},
      "no-rn-namespace-import": {},
      "no-unlabeled-icon-pressable": {},
      "hoist-stateless-function": {},
      "no-manual-memo": {},
      "no-dynamic-import": {},
    },
  },
  {
    meta: { name: "@ashstack/unistyles" },
    url: at("../react-native/rules/unistyles/index.js"),
    option: "unistyles",
    packages: ["react-native-unistyles"],
    restrictedImports: {
      paths: [
        {
          name: "react-native",
          importNames: ["StyleSheet"],
          message: "Import `StyleSheet` from `react-native-unistyles` instead of `react-native`.",
        },
        {
          name: "react-native",
          importNames: ["useWindowDimensions", "Dimensions"],
          message:
            "Read screen size from `rt.screen` inside `StyleSheet.create`, or `UnistylesRuntime.screen` outside it, instead of the `Dimensions` APIs.",
        },
        {
          name: "react-native",
          importNames: ["SafeAreaView"],
          message:
            'Set `contentInsetAdjustmentBehavior="automatic"` on the scroll view, or apply `rt.insets` from `react-native-unistyles`, instead of `SafeAreaView`.',
        },
        {
          name: "react-native-safe-area-context",
          importNames: ["useSafeAreaInsets", "useSafeAreaFrame", "SafeAreaView"],
          message:
            "Read safe-area values from `rt.insets`, or `UnistylesRuntime.insets` outside a stylesheet, in `react-native-unistyles`.",
        },
      ],
    },
    rules: {
      "animated-theme": {},
      "content-container": {},
      "in-sheet": {},
      insets: {},
      "no-hardcoded-color": {},
      "no-hardcoded-spacing": {},
      "no-margin": {},
      "no-style-spread": {},
      "no-unused-styles": {},
      "rtl-style-call": {},
      "theme-screen-component": {},
      "theme-style-attr": {},
    },
  },
  {
    meta: { name: "@ashstack/legend-list" },
    url: at("../react-native/rules/legend-list/index.js"),
    option: "legendList",
    packages: ["@legendapp/list"],
    restrictedImports: {
      paths: [
        {
          name: "react-native",
          importNames: ["FlatList", "SectionList", "VirtualizedList"],
          message:
            "Render this list with `LegendList` from `@legendapp/list/react-native`; a `ScrollView` plus `map` is fine for fewer than 20 static items.",
        },
        {
          name: "@shopify/flash-list",
          message:
            "Import `LegendList` from `@legendapp/list/react-native` — Legend List replaced FlashList in this stack.",
        },
      ],
      patterns: [
        {
          group: ["@legendapp/list"],
          message: "Import from the platform entrypoint `@legendapp/list/react-native`, not the package root.",
        },
      ],
    },
    rules: {
      "required-props": {},
      "no-index-key-extractor": {},
      "no-remount-key": {},
      "no-inline-render-item-props": {},
      "no-mixed-children": {},
      "no-flex-in-content-container": {},
      "typed-items-need-item-type": {},
      "no-scrollview-map": {},
      "no-unsupported-props": {},
    },
  },
  {
    meta: { name: "@ashstack/legend-state" },
    url: at("../react-native/rules/legend-state/index.js"),
    option: "legendState",
    packages: ["@legendapp/state"],
    restrictedImports: {
      paths: [
        {
          name: "@legendapp/state/react",
          importNames: ["use$", "useSelector"],
          message: "Use `useValue` from `@legendapp/state/react`; `use$` and `useSelector` are deprecated.",
        },
      ],
    },
    rules: {
      "no-assignment": {},
      naming: {},
      "no-nested-observable": {},
      "no-react-mirror": {},
      "no-untracked-get-in-jsx": {},
      "no-peek-in-selector": {},
      "no-object-selector": {},
      "no-observable-in-component": {},
    },
  },
  {
    meta: { name: "@ashstack/reanimated" },
    url: at("../react-native/rules/reanimated/index.js"),
    option: "reanimated",
    packages: ["react-native-reanimated"],
    restrictedImports: {
      paths: [
        {
          name: "react-native",
          importNames: ["Animated"],
          message: "Use `react-native-reanimated` instead of React Native's `Animated` API.",
        },
        {
          name: "react-native-reanimated",
          importNames: ["runOnJS", "runOnUI"],
          message:
            "Use `scheduleOnRN` and `scheduleOnUI` from `react-native-worklets`; `runOnJS` and `runOnUI` are deprecated.",
        },
        {
          name: "react-native-worklets",
          importNames: ["runOnJS", "runOnUI"],
          message:
            "Use `scheduleOnRN` and `scheduleOnUI` from `react-native-worklets`; `runOnJS` and `runOnUI` are deprecated.",
        },
      ],
    },
    rules: {
      "animated-reaction-safety": {},
      "animated-style-needs-animated-component": {},
      "animated-updater-purity": {},
      "gpu-properties-only": {},
      "hoist-layout-animation-builder": {},
      "interpolate-needs-clamp": {},
      "no-shared-value-dot-value": {},
      "no-react-state-from-continuous-worklet": {},
      "prefer-lazy-shared-value-initializer": {},
      "schedule-on-rn-scope": {},
      "shared-value-usage": {},
    },
  },
  {
    meta: { name: "@ashstack/turbo-image" },
    url: at("../react-native/rules/turbo-image/index.js"),
    option: "turboImage",
    packages: ["react-native-turbo-image"],
    rules: {
      "require-resize": {},
      "require-cache-policy": {},
    },
  },
  {
    meta: { name: "@ashstack/skia" },
    url: at("../react-native/rules/skia/index.js"),
    option: "skia",
    packages: ["@shopify/react-native-skia"],
    restrictedImports: {
      paths: [
        {
          name: "@shopify/react-native-skia",
          importNames: ["usePathValue", "usePathInterpolation"],
          message:
            "Keep one stable `SkPath` buffer and mutate it inside `useDerivedValue`, with consumers reading the driving shared value. These legacy path-value hooks self-dirty Reanimated mappers and re-record idle canvases.",
        },
      ],
    },
    rules: {
      "canvas-opaque": {},
    },
  },
  {
    meta: { name: "@ashstack/keyboard" },
    url: at("../react-native/rules/keyboard/index.js"),
    option: "keyboard",
    packages: ["react-native-keyboard-controller"],
    restrictedImports: {
      paths: [
        {
          name: "react-native",
          importNames: ["KeyboardAvoidingView"],
          message:
            "Import `KeyboardAvoidingView` from `react-native-keyboard-controller` — same props, and it tracks the keyboard per frame instead of waiting for Android's post-animation `keyboardDidShow`. For a scrolling form use its `KeyboardAwareScrollView`; to just shift a view, use `rt.insets.ime`.",
        },
      ],
    },
    rules: {},
  },
];
