// @ashstack/lint — core entry. Base TypeScript rules for any project (backend, CLI, library).
// Type-aware rules (typescript/no-floating-promises, no-unnecessary-condition, …) require
// running oxlint with --type-aware and the oxlint-tsgolint peer installed.
import { detect } from "../lib/detect.js";
import { ownPlugin } from "../lib/resolve.js";

/**
 * Base entry — strict TypeScript rules for any project (backend, CLI, library).
 * Library rule groups (zod) auto-enable when the consumer depends on the
 * library; pass an explicit boolean to force either way.
 */
const core = (options = {}) => {
  const zod = detect(options.zod, ["zod"]);

  return {
    plugins: ["eslint", "typescript", "import", "unicorn", "promise", "oxc"],
    jsPlugins: [ownPlugin("core/rules/ash.js"), ...(zod ? [ownPlugin("core/rules/zod.js")] : [])],
    env: { builtin: true, es2024: true },
    categories: {
      correctness: "error",
      suspicious: "error",
      perf: "error",
      pedantic: "off",
      style: "off",
      restriction: "off",
      nursery: "off",
    },
    rules: {
      "array-callback-return": "error",
      "constructor-super": "error",
      "default-param-last": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "for-direction": "error",
      "getter-return": "error",
      "func-style": ["error", "expression"],
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-param-reassign": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "off",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-undef": "off",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-useless-catch": "error",
      "no-useless-constructor": "error",
      "no-useless-escape": "error",
      "no-var": "error",
      "no-with": "error",
      "object-shorthand": ["error", "methods"],
      "prefer-rest-params": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-unused-vars": [
        "error",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          ignoreRestSiblings: true,
          fix: { imports: "safe-fix" },
        },
      ],
      "no-use-before-define": "off",
      complexity: ["error", { max: 12 }],
      "max-depth": ["error", 3],
      "max-params": ["error", 4],
      "max-lines": ["error", { max: 300, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["error", { max: 250, skipBlankLines: true, skipComments: true }],
      "eslint/no-await-in-loop": "error",
      "eslint/no-console": "off",
      "eslint/no-constant-binary-expression": "off",
      "eslint/no-control-regex": "error",
      "eslint/no-else-return": "error",
      "eslint/no-empty": "error",
      "eslint/no-empty-function": "error",
      "eslint/no-new": "off",
      "eslint/no-self-compare": "error",
      "eslint/no-shadow": "error",
      "eslint/no-template-curly-in-string": "error",
      "eslint/no-unassigned-vars": "off",
      "eslint/no-underscore-dangle": "off",
      "eslint/no-unmodified-loop-condition": "off",
      "eslint/no-unused-expressions": "off",
      "eslint/no-useless-concat": "off",
      "eslint/preserve-caught-error": "off",
      "eslint/prefer-arrow-callback": "error",
      "eslint/prefer-const": "error",
      "eslint/prefer-template": "error",
      "typescript/consistent-type-imports": "error",
      "typescript/dot-notation": "error",
      "typescript/no-confusing-void-expression": "error",
      "typescript/no-empty-object-type": ["error", { allowInterfaces: "with-single-extends" }],
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-extraneous-class": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-misused-promises": ["error", { checksVoidReturn: false }],
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-non-null-assertion": "error",
      "typescript/no-unnecessary-boolean-literal-compare": "error",
      "typescript/no-unnecessary-condition": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unsafe-type-assertion": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/require-await": "error",
      "typescript/switch-exhaustiveness-check": "error",
      "import/no-commonjs": "off",
      "import/no-cycle": "error",
      "import/no-duplicates": "error",
      "import/no-named-as-default": "off",
      "import/no-named-as-default-member": "off",
      "import/no-self-import": "off",
      "import/no-unassigned-import": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/no-array-reverse": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/no-empty-file": "off",
      "unicorn/no-new-array": "off",
      "unicorn/no-useless-fallback-in-spread": "off",
      "unicorn/no-useless-spread": "off",
      "unicorn/prefer-add-event-listener": "off",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-logical-operator-over-ternary": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/require-module-specifiers": "off",
      "unicorn/throw-new-error": "error",
      "promise/always-return": "off",
      "promise/no-callback-in-promise": "off",
      "promise/no-multiple-resolved": "off",
      "promise/no-promise-in-callback": "off",
      "oxc/no-async-endpoint-handlers": "off",
      "ash/comment-escape-hatch": "error",
      ...(zod && { "zod/prefer-enum": "error" }),
    },
    overrides: [
      {
        files: ["**/*.tsx"],
        rules: { "func-style": "off" },
      },
      {
        files: ["**/*.d.ts"],
        rules: { "typescript/no-explicit-any": "off" },
      },
      {
        files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx", "**/__tests__/**"],
        rules: {
          "typescript/await-thenable": "off",
          "typescript/no-unsafe-type-assertion": "off",
          "typescript/require-await": "off",
          "typescript/unbound-method": "off",
          "ash/comment-escape-hatch": "off",
        },
      },
    ],
  };
};

export default core;
