// Generates packages/lint/RULES.md from the plugins themselves: each rule's
// meta.docs.description, meta.schema (options), and its bad/good fixtures as
// examples. Run with --check in CI to fail when the file is stale or a rule
// is missing its description.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const lintDir = join(import.meta.dir, "..", "packages", "lint");
const outPath = join(lintDir, "RULES.md");
const check = process.argv.includes("--check");

// module -> plugin file + when the module's rules are active
const MODULES: [string, string, string][] = [
  ["core", "src/core/rules/base.js", "always on via `core()` (except the opt-in rules noted below)"],
  ["zod", "src/core/rules/zod.js", "auto-enabled by `core()` when `zod` is a dependency"],
  ["query", "src/react/rules/query.js", "auto-enabled by `react()` when `@tanstack/react-query` is a dependency"],
  ["zustand", "src/react/rules/zustand.js", "auto-enabled by `react()` when `zustand` is a dependency"],
  ["i18n", "src/react/rules/i18n.js", "auto-enabled by `react()` when an i18n library is a dependency"],
  ["react-native", "src/react-native/rules/base.js", "always on via `reactNative()`"],
  ["unistyles", "src/react-native/rules/unistyles.js", "auto-enabled when `react-native-unistyles` is a dependency"],
  ["legend-list", "src/react-native/rules/legend-list.js", "auto-enabled when `@legendapp/list` is a dependency"],
  ["legend-state", "src/react-native/rules/legend-state.js", "auto-enabled when `@legendapp/state` is a dependency"],
  ["reanimated", "src/react-native/rules/reanimated.js", "auto-enabled when `react-native-reanimated` is a dependency"],
  [
    "turbo-image",
    "src/react-native/rules/turbo-image.js",
    "auto-enabled when `react-native-turbo-image` is a dependency",
  ],
  ["skia", "src/react-native/rules/skia.js", "auto-enabled when `@shopify/react-native-skia` is a dependency"],
  [
    "keyboard",
    "src/react-native/rules/keyboard.js",
    "auto-enabled when `react-native-keyboard-controller` is a dependency",
  ],
];

// rules shipped disabled; consumers opt in per project
const OFF_BY_DEFAULT = new Set(["core/no-comments", "core/use-design-system", "core/components-tsx-only"]);
// gated on something other than the module itself
const SPECIAL = new Map([["react-native/no-manual-memo", "only when a React Compiler package is a dependency"]]);

const fixture = (module: string, rule: string, file: string) => {
  for (const ext of [".tsx", ".ts"]) {
    const p = join(lintDir, "fixtures", module, rule, `${file}${ext}`);
    if (existsSync(p)) return readFileSync(p, "utf8").trim();
  }
  return null;
};

const renderSchema = (schema: unknown) =>
  schema ? "\n**Options**\n\n```jsonc\n" + JSON.stringify(schema, null, 2) + "\n```\n" : "";

const failures: string[] = [];
const toc: string[] = [];
const body: string[] = [];

for (const [module, file, when] of MODULES) {
  const plugin = (await import(join(lintDir, file))).default;
  const names = Object.keys(plugin.rules);
  toc.push(
    `- [\`@ashstack/${module}\`](#ashstack${module.replace(/-/g, "")}) — ${names.length} rule${names.length > 1 ? "s" : ""}`
  );
  body.push(`## \`@ashstack/${module}\`\n`, `_${when}._\n`);

  for (const name of names) {
    const rule = plugin.rules[name];
    const description = rule.meta?.docs?.description;
    if (!description) failures.push(`@ashstack/${module}/${name}: missing meta.docs.description`);

    body.push(`### \`@ashstack/${module}/${name}\`\n`, `${description ?? "_undocumented_"}\n`);
    if (OFF_BY_DEFAULT.has(`${module}/${name}`)) body.push(`> Off by default — opt in per project.\n`);
    const special = SPECIAL.get(`${module}/${name}`);
    if (special) body.push(`> Enabled ${special}.\n`);
    body.push(renderSchema(rule.meta?.schema));

    const bad = fixture(module, name, "bad");
    const good = fixture(module, name, "good");
    if (bad) body.push(`**Fails**\n\n\`\`\`tsx\n${bad}\n\`\`\`\n`);
    if (good) body.push(`**Passes**\n\n\`\`\`tsx\n${good}\n\`\`\`\n`);
  }
}

const doc = [
  "<!-- GENERATED by scripts/generate-rule-docs.ts - do not edit by hand. `bun run docs:rules` regenerates it. -->",
  "",
  "# @ashstack/lint — custom rules",
  "",
  "Every custom rule this package ships, generated from the rules' own metadata and fixtures.",
  "Built-in oxlint rules (eslint/, typescript/, react/, …) are documented at https://oxc.rs/docs/guide/usage/linter/rules.html.",
  "",
  'Disable any rule by its full id in your `rules` block, e.g. `"@ashstack/unistyles/no-margin": "off"`.',
  "",
  ...toc,
  "",
  ...body,
].join("\n");

if (failures.length > 0) {
  console.error(`RULE DOC FAILURES (${failures.length}):\n` + failures.map(f => `  - ${f}`).join("\n"));
  process.exit(1);
}

if (check) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current !== doc) {
    console.error("RULES.md is stale - run `bun run docs:rules` and commit the result.");
    process.exit(1);
  }
  console.log("rule docs ok");
} else {
  writeFileSync(outPath, doc);
  console.log(`wrote ${outPath}`);
}
