// Generates packages/lint/RULES.md from the built module registry: each rule's
// meta.docs.description, meta.schema (options), activation, and its bad/good
// fixtures as examples. Run with --check in CI to fail when the file is stale
// or a rule is missing its description. Run `bun run build` first.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { allModules, shortName } from "../packages/lint/dist/lib/registry.js";

const lintDir = join(import.meta.dir, "..", "packages", "lint");
const outPath = join(lintDir, "RULES.md");
const check = process.argv.includes("--check");

const fixture = (module: string, rule: string, file: string) => {
  for (const ext of [".tsx", ".ts"]) {
    const p = join(lintDir, "fixtures", module, rule, `${file}${ext}`);
    if (existsSync(p)) return readFileSync(p, "utf8").trim();
  }
  return null;
};

const failures: string[] = [];
const toc: string[] = [];
const body: string[] = [];

for (const module of allModules) {
  const dir = shortName(module);
  const names = Object.keys(module.rules);
  toc.push(
    `- [\`${module.meta.name}\`](#${module.meta.name.replace(/[@/]/g, "").replace(/-/g, "")}) — ${names.length} rule${names.length > 1 ? "s" : ""}`
  );
  body.push(`## \`${module.meta.name}\`\n`, `_${module.docsWhen}._\n`);

  for (const name of names) {
    const rule = module.rules[name];
    const description = rule.meta?.docs?.description;
    if (!description) failures.push(`${module.meta.name}/${name}: missing meta.docs.description`);

    body.push(`### \`${module.meta.name}/${name}\`\n`, `${description ?? "_undocumented_"}\n`);
    if (rule.meta?.defaultOff) body.push(`> Off by default — opt in per project.\n`);
    if (rule.meta?.packages) {
      body.push(`> Enabled only when one of ${rule.meta.packages.map(p => `\`${p}\``).join(", ")} is a dependency.\n`);
    }
    if (rule.meta?.schema) {
      body.push("**Options**\n\n```jsonc\n" + JSON.stringify(rule.meta.schema, null, 2) + "\n```\n");
    }

    const bad = fixture(dir, name, "bad");
    const good = fixture(dir, name, "good");
    if (bad) body.push(`**Fails**\n\n\`\`\`tsx\n${bad}\n\`\`\`\n`);
    if (good) body.push(`**Passes**\n\n\`\`\`tsx\n${good}\n\`\`\`\n`);
  }
}

const doc = [
  "<!-- GENERATED by scripts/generate-rule-docs.ts - do not edit by hand. `bun run docs:rules` regenerates it. -->",
  "",
  "# @ashstack/lint — custom rules",
  "",
  "Every custom rule this package ships, generated from the modules' own metadata and fixtures.",
  "Built-in oxlint rules (eslint/, typescript/, react/, …) are documented at https://oxc.rs/docs/guide/usage/linter/rules.html.",
  "",
  'Disable any rule by its full id in your `rules` block, e.g. `"@ashstack/unistyles/no-margin": "off"`.',
  "",
  ...toc,
  "",
  ...body,
].join("\n");

if (failures.length > 0) {
  console.error(`RULE DOC FAILURES (${failures.length}):\n` + failures.map(f => `  - ${f}`).join("\n"));
  process.exit(1);
}

if (check) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current !== doc) {
    console.error("RULES.md is stale - run `bun run docs:rules` and commit the result.");
    process.exit(1);
  }
  console.log("rule docs ok");
} else {
  writeFileSync(outPath, doc);
  console.log(`wrote ${outPath}`);
}
