import { join } from "node:path";

import type { ModuleManifest, Rule } from "../packages/lint/dist/lib/types.js";
import { coreModules, reactModules, reactNativeModules } from "../packages/lint/dist/modules.js";
import { effectsModule, emit, formatGenerated, type Generated, ruleNotes, sectionLink } from "./shared.js";

/**
 * Write the `oxlint` module augmentation that types every rule id this package
 * ships, so an editor answers "what does this rule do, and what does it take?"
 * on hover instead of sending the reader to RULES.md.
 *
 * One file per entry, each augmenting oxlint's own `DummyRuleMap`: a config
 * that imports `@ashstack/lint/core` sees the core ids and nothing about
 * React. The files are types only — the `export type` re-exports that reach
 * them leave no runtime import behind, so a consumer's config graph does not
 * grow. Layout is oxfmt's job, so nothing here indents.
 *
 * Writing the files is the script's job, not the module's: tests import the
 * pure parts.
 */
const outDir = join(import.meta.dir, "..", "packages", "lint", "src", "lib", "rule-types");

type Schema = Extract<NonNullable<Rule["meta"]["schema"]>, unknown[]>[number];

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const propertyKey = (name: string): string => (IDENTIFIER.test(name) ? name : JSON.stringify(name));

const objectType = (schema: Schema): string => {
  const { properties } = schema;
  if (properties === undefined) {
    const extra = schema.additionalProperties;
    return `Record<string, ${typeof extra === "object" ? tsType(extra) : "unknown"}>`;
  }
  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const fields = Object.entries(properties).map(
    ([name, value]) => `${propertyKey(name)}${required.has(name) ? "" : "?"}: ${tsType(value)}`
  );
  return `{ ${fields.join("; ")} }`;
};

/** The TypeScript spelling of one rule option's JSON schema. */
export const tsType = (schema: Schema): string => {
  if (schema.enum) return schema.enum.map(value => JSON.stringify(value)).join(" | ");
  if (schema.anyOf) return schema.anyOf.map(tsType).join(" | ");
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "string") return "string";
  if (schema.type === "object") return objectType(schema);
  const { items } = schema;
  if (schema.type !== "array" || items === undefined || Array.isArray(items)) return "unknown";
  return `Array<${tsType(items)}>`;
};

/** Every shape oxlint accepts for a rule: a bare severity, or severity plus as many options as it declares. */
export const settingType = (rule: Rule): string => {
  const { schema } = rule.meta;
  if (!Array.isArray(schema)) return "AllowWarnDeny | [AllowWarnDeny]";
  const types = schema.map(tsType);
  const tuples = types.map((_, index) => `[AllowWarnDeny, ${types.slice(0, index + 1).join(", ")}]`);
  return ["AllowWarnDeny", "[AllowWarnDeny]", ...tuples].join(" | ");
};

/** A JSDoc block from paragraphs, blank-line separated the way a hover renders them. */
const jsdoc = (paragraphs: string[]): string[] => [
  "/**",
  ...paragraphs
    .join("\n\n")
    .replaceAll("*/", "*\\/")
    .split("\n")
    .map(line => ` * ${line}`.trimEnd()),
  " */",
];

/** One rule as a documented member of the augmented map. */
export const ruleMember = ([id, rule]: RuleEntry): string[] =>
  jsdoc([rule.meta.docs.description, ...ruleNotes(rule.meta), `@see ${sectionLink(id)}`]).concat(
    `${JSON.stringify(id)}?: ${settingType(rule)};`
  );

export type RuleEntry = [id: string, rule: Rule];

export const rulesOf = (modules: ModuleManifest[]): RuleEntry[] =>
  modules.flatMap(module =>
    Object.entries(module.rules).map(([name, rule]): RuleEntry => [`${module.meta.name}/${name}`, rule])
  );

export interface Tier {
  /** File name under `lib/rule-types/`. */
  file: string;
  /** Name of the exported union of this tier's rule ids. */
  typeName: string;
  /** The entry that adds these rules, as RULES.md heads its section. */
  entry: string;
  modules: ModuleManifest[];
}

export const fileFor = ({ typeName, entry, modules }: Tier): string => {
  const rules = rulesOf(modules);
  return [
    "// GENERATED by scripts/generate-rule-types.ts - do not edit by hand. `bun run types:rules` regenerates it.",
    "",
    'import type { AllowWarnDeny } from "oxlint";',
    "",
    `/** Every rule id \`${entry}\` adds on top of the entry below it. */`,
    `export type ${typeName} = ${rules.map(([id]) => JSON.stringify(id)).join(" | ")};`,
    "",
    'declare module "oxlint" {',
    "interface DummyRuleMap {",
    ...rules.flatMap(ruleMember),
    "}",
    "}",
    "",
  ].join("\n");
};

const main = async (): Promise<void> => {
  const tiers: Tier[] = [
    { file: "core.ts", typeName: "CoreRuleId", entry: "core()", modules: coreModules },
    { file: "react.ts", typeName: "ReactRuleId", entry: "react()", modules: [...reactModules, await effectsModule()] },
    { file: "react-native.ts", typeName: "ReactNativeRuleId", entry: "react-native()", modules: reactNativeModules },
  ];

  const generated = tiers.map((tier): Generated => {
    const path = join(outDir, tier.file);
    return [path, formatGenerated(path, fileFor(tier))];
  });

  emit(generated, "rule types", "bun run types:rules");
};

if (import.meta.main) await main();
