import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import type { ModuleManifest, Rule } from "../packages/lint/dist/lib/types.js";
import { coreModules, reactModules, reactNativeModules } from "../packages/lint/dist/modules.js";
import { emit, formatGenerated } from "./shared.js";

/**
 * Write the metadata an entry needs, so no config imports rule code.
 *
 * A config reads a module's name, its plugin path, what gates it, and two
 * flags per rule. oxlint loads the rule implementations itself from that path.
 * Importing the manifests directly put all 74 of them — 104 KB, three quarters
 * of the graph — in front of every consumer for nothing.
 *
 * Layout is oxfmt's job, so nothing here indents.
 */
const lintDir = join(import.meta.dir, "..", "packages", "lint");
const outPath = join(lintDir, "src", "lib", "registry.ts");

/** Where the module's plugin file sits relative to `lib/registry.js`, which resolves it at runtime. */
const pluginPath = (module: ModuleManifest): string =>
  relative(join(lintDir, "dist", "lib"), fileURLToPath(module.url)).replaceAll("\\", "/");

/** Module fields a config reads only when the module has them. */
const OPTIONAL = ["option", "packages", "restrictedImports"] as const;

/** The two flags that decide whether a rule is on, and nothing else from its meta. */
const ruleFlags = (rule: Rule): string => {
  const flags = [
    ...(rule.meta.defaultOff === true ? ["defaultOff: true"] : []),
    ...(rule.meta.packages ? [`packages: ${JSON.stringify(rule.meta.packages)}`] : []),
  ];
  return flags.length === 0 ? "{}" : `{ ${flags.join(", ")} }`;
};

const entryFor = (module: ModuleManifest): string[] => [
  "{",
  `meta: { name: ${JSON.stringify(module.meta.name)} },`,
  `url: at(${JSON.stringify(pluginPath(module))}),`,
  ...OPTIONAL.flatMap(key => (module[key] === undefined ? [] : [`${key}: ${JSON.stringify(module[key])},`])),
  "rules: {",
  ...Object.entries(module.rules).map(([name, rule]) => `${JSON.stringify(name)}: ${ruleFlags(rule)},`),
  "},",
  "},",
];

const listFor = (name: string, modules: ModuleManifest[]): string[] => [
  `export const ${name}: ModuleMeta[] = [`,
  ...modules.flatMap(entryFor),
  "];",
  "",
];

const registry = [
  "// GENERATED by scripts/generate-registry.ts - do not edit by hand. `bun run registry` regenerates it.",
  "",
  'import type { ModuleMeta } from "./types.js";',
  "",
  "const at = (path: string): string => new URL(path, import.meta.url).href;",
  "",
  ...listFor("coreRegistry", coreModules),
  ...listFor("reactRegistry", reactModules),
  ...listFor("reactNativeRegistry", reactNativeModules),
].join("\n");

emit([[outPath, formatGenerated(outPath, registry)]], "registry", "bun run registry");
