import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import {
  banGroups,
  core,
  coreModules,
  react,
  reactModules,
  reactNative,
  reactNativeModules,
} from "../packages/lint/dist/index.js";
import { shortName } from "../packages/lint/dist/lib/module.js";
import type {
  BanGroup,
  ModuleManifest,
  OxlintConfig,
  RestrictedImports,
  Rule,
} from "../packages/lint/dist/lib/types.js";
import { validateRuleDocLinks } from "./rule-doc-links.js";
import { cell, type EntryConfig, optionsDoc } from "./rule-options-doc.js";
import { anchor, effectsModule, emit, type Generated, list, ruleStatus } from "./shared.js";

const lintDir = join(import.meta.dir, "..", "packages", "lint");
const outPath = join(lintDir, "RULES.md");
const generatedNotice =
  "<!-- GENERATED by scripts/generate-rule-docs.ts - do not edit by hand. `bun run docs:rules` regenerates it. -->";

const OXLINT_RULE_DOCS = "https://oxc.rs/docs/guide/usage/linter/rules";
const linkedRuleId = (ruleId: string): string => {
  const [plugin = "eslint", rule = ruleId] = ruleId.includes("/") ? ruleId.split("/") : ["eslint", ruleId];
  const pluginPath = plugin.replace(/-/g, "_");
  return `[\`${ruleId}\`](${OXLINT_RULE_DOCS}/${pluginPath}/${rule}.html)`;
};

const builtInRules = (config: OxlintConfig): Record<string, unknown> =>
  Object.fromEntries(
    Object.entries(config.rules ?? {}).filter(([id]) => !id.startsWith("@ashstack/") && id !== "no-restricted-imports")
  );

const builtInTable = (config: OxlintConfig, inherited: Record<string, unknown>): string[] => {
  const rows = Object.entries(builtInRules(config))
    .filter(([id, setting]) => JSON.stringify(inherited[id]) !== JSON.stringify(setting))
    .map(([id, setting]) => `| ${linkedRuleId(id)} | \`${JSON.stringify(setting)}\` |`);
  if (rows.length === 0) return ["_No built-in rule settings change here._", ""];
  return ["| Rule | Setting |", "| --- | --- |", ...rows, ""];
};

const banList = (bans: RestrictedImports): string[] => [
  ...(bans.paths ?? []).map(p => `- \`${(p.importNames ?? ["*"]).join("`, `")}\` from \`${p.name}\``),
  ...(bans.patterns ?? []).map(p => `- any import of \`${p.group.join("`, `")}\``),
];

const fixtureSource = (moduleDir: string, rule: string, fixture: "bad" | "good"): string | null => {
  const path = join(lintDir, "fixtures", moduleDir, rule, `${fixture}.tsx`);
  return existsSync(path) ? readFileSync(path, "utf8").trim() : null;
};

const activationNotes = (module: ModuleManifest, rule: Rule, id: string): string[] => [
  ruleStatus(module, rule),
  "",
  ...optionsDoc(rule, id, entryConfigs),
];

const examples = (moduleDir: string, name: string): string[] => {
  const bad = fixtureSource(moduleDir, name, "bad");
  const good = fixtureSource(moduleDir, name, "good");
  return [
    ...(bad ? ["**Fails**", "", "```tsx", bad, "```", ""] : []),
    ...(good ? ["**Passes**", "", "```tsx", good, "```", ""] : []),
  ];
};

const ruleSection = (module: ModuleManifest, name: string, rule: ModuleManifest["rules"][string]): string[] => [
  `## \`${module.meta.name}/${name}\``,
  "",
  rule.meta.docs.description,
  "",
  ...activationNotes(module, rule, `${module.meta.name}/${name}`),
  ...examples(shortName(module), name),
];

const moduleSection = (module: ModuleManifest): string[] => {
  const lines = [
    generatedNotice,
    "",
    "[Rule router](../RULES.md)",
    "",
    `# \`${module.meta.name}\``,
    "",
    `_${module.docsWhen}._`,
    "",
    ...Object.keys(module.rules).map(name => `- [\`${name}\`](#${anchor(`${module.meta.name}/${name}`)})`),
    "",
  ];
  if (module.restrictedImports) {
    lines.push("**Import bans that ship with this module**", "", ...banList(module.restrictedImports), "");
  }
  for (const [name, rule] of Object.entries(module.rules)) lines.push(...ruleSection(module, name, rule));
  return lines;
};

const banGroupSection = (groups: BanGroup[]): string[] => [
  "### Import bans without a module",
  "",
  "_Auto-detected from your dependencies; these carry no rules of their own._",
  "",
  ...groups.flatMap(group => [
    `**\`${group.packages.join("` / `")}\` installed**`,
    "",
    ...banList(group.restrictedImports),
    "",
  ]),
];

interface Entry {
  entry: string;
  summary: string;
  config: OxlintConfig;
  inherited: Record<string, unknown>;
  modules: ModuleManifest[];
  extra?: string[];
}

const entrySection = ({ entry, summary, config, inherited, modules, extra = [] }: Entry): string[] => [
  generatedNotice,
  "",
  "[Rule router](../../RULES.md)",
  "",
  `# \`${entry}\``,
  "",
  summary,
  "",
  `Plugins: ${(config.plugins ?? []).map(p => `\`${p}\``).join(", ")}.`,
  "",
  "## Built-in rules",
  "",
  ...builtInTable(config, inherited),
  "## Modules added by this entry",
  "",
  ...modules.map(module => `- [\`${module.meta.name}\`](../${shortName(module)}.md) — ${module.docsWhen}.`),
  "",
  ...extra,
];

/** Every module forced on, so a count does not depend on what the repo running this depends on. */
const allOn = (modules: ModuleManifest[]): Record<string, boolean> =>
  Object.fromEntries(modules.flatMap(m => (m.option === undefined ? [] : [[m.option, true]])));

const severityOf = (setting: unknown): string => {
  if (typeof setting === "string") return setting;
  return Array.isArray(setting) && typeof setting[0] === "string" ? setting[0] : "";
};

const enabledRules = (config: OxlintConfig): number =>
  Object.values(config.rules ?? {}).filter(setting => severityOf(setting) !== "off").length;

const customRules = (modules: ModuleManifest[]): number =>
  modules.reduce((total, m) => total + Object.values(m.rules).filter(rule => !rule.meta.defaultOff).length, 0);

const detectingModules = (modules: ModuleManifest[]): number =>
  modules.filter(m => (m.packages ?? []).length > 0).length;

const coreConfig = core();
const reactConfig = react();
const reactNativeConfig = reactNative();

/** Layering order, so a rule's `Set by:` line reads top down and skips what an entry inherits. */
const entryConfigs: EntryConfig[] = [
  ["core()", coreConfig],
  ["react()", reactConfig],
  ["react-native()", reactNativeConfig],
];

const reactAll = [...coreModules, ...reactModules];
const reactDocsModules = [...reactModules, await effectsModule()];
const reactNativeAll = [...reactAll, ...reactNativeModules];

const counts = {
  core: enabledRules(core(allOn(coreModules))),
  react: enabledRules(react(allOn(reactAll))),
  reactNative: enabledRules(reactNative(allOn(reactNativeAll))),
  custom: customRules(reactNativeAll),
  detecting: detectingModules(reactNativeAll),
};

/**
 * The rules a consumer has to ask for, named in full. Read off the
 * `defaultOff` flags themselves, so a rule that stops being opt-in cannot
 * leave a README claiming it still is.
 */
const optInIds = reactNativeAll.flatMap(module =>
  Object.entries(module.rules)
    .filter(([, rule]) => rule.meta.defaultOff === true)
    .map(([name]) => `\`${module.meta.name}/${name}\``)
);

const optIn =
  optInIds.length === 0
    ? "Every rule is on by default."
    : `Off by default, since they need a team decision first: ${list(optInIds, "and")}.`;

/** On in a bare oxlint install, so listing them as ours would be a lie. */
const OXLINT_DEFAULT_PLUGINS = ["eslint", "typescript", "unicorn", "oxc"];

const backticked = (names: string[]): string => names.map(name => `\`${name}\``).join(", ");

const ourPlugins = [
  ...new Set([coreConfig, reactConfig, reactNativeConfig].flatMap(config => config.plugins ?? [])),
].filter(plugin => !OXLINT_DEFAULT_PLUGINS.includes(plugin));

const entries: Entry[] = [
  {
    entry: "core()",
    summary: "Any TypeScript project — backend, CLI, library.",
    config: coreConfig,
    inherited: {},
    modules: coreModules,
  },
  {
    entry: "react()",
    summary:
      "React on the web. Adds the you-might-not-need-an-effect rules as `@ashstack/effects/`, alongside oxlint's own react plugin.",
    config: reactConfig,
    inherited: builtInRules(coreConfig),
    modules: reactDocsModules,
  },
  {
    entry: "react-native()",
    summary: "Expo and React Native.",
    config: reactNativeConfig,
    inherited: builtInRules(reactConfig),
    modules: reactNativeModules,
    extra: banGroupSection(banGroups),
  },
];

const doc = [
  generatedNotice,
  "",
  "# @ashstack/lint rules",
  "",
  "Start here, then open only the page relevant to the task. For a diagnostic such as `@ashstack/unistyles/no-margin`, open the `@ashstack/unistyles` page and follow its rule index. Each rule states its default status, options, and examples where available.",
  "",
  "`core()`, `react()` and `react-native()` each contain the one before, so a section's built-in table lists only the settings that entry changes. Built-in rules link to their upstream page.",
  "",
  'Turn any rule off by id in your own `rules` block: `"@ashstack/unistyles/no-margin": "off"`.',
  "",
  `Each entry lists the oxlint plugins it turns on, below. You never need to add them: your own \`plugins\` array is added to the entry's set, not swapped for it. A bare oxlint install runs ${backticked(OXLINT_DEFAULT_PLUGINS)}; ${backticked(ourPlugins)} come from here.`,
  "",
  `Counting what each entry sets with every module on: **${counts.core}** rules for plain TypeScript, **${counts.react}** with React, **${counts.reactNative}** on React Native, ${counts.custom} of them written for this package. oxlint's own \`correctness\` category runs alongside these.`,
  "",
  "## Entry settings",
  "",
  "| Read when | Page |",
  "| --- | --- |",
  ...entries.map(
    ({ entry, summary }) =>
      `| ${summary} Built-in settings and plugins. | [\`${entry}\`](rules/entries/${anchor(entry)}.md) |`
  ),
  "",
  "## Rule namespaces",
  "",
  "Match the diagnostic prefix, or use the activation column when configuring a library. Entries inherit all modules from the entry before them.",
  "",
  "| Diagnostic prefix / page | Added by | Rules | Activation / read when |",
  "| --- | --- | --- | --- |",
  ...entries.flatMap(({ entry, modules }) =>
    modules.map(
      module =>
        `| [\`${module.meta.name}\`](rules/${shortName(module)}.md) | \`${entry}\` | ${Object.keys(module.rules).length || "Import bans only"} | ${cell(module.docsWhen)} |`
    )
  ),
  "",
].join("\n");

const pages: Generated[] = [
  [outPath, doc],
  ...entries.map((entry): Generated => [
    join(lintDir, "rules", "entries", `${anchor(entry.entry)}.md`),
    entrySection(entry).join("\n"),
  ]),
  ...entries.flatMap(({ modules }) =>
    modules.map((module): Generated => [
      join(lintDir, "rules", `${shortName(module)}.md`),
      moduleSection(module).join("\n"),
    ])
  ),
];

/** The generated regions each README carries, keyed by marker name. */
const readmeRegions: [path: string, regions: Record<string, string>][] = [
  [
    join(import.meta.dir, "..", "README.md"),
    {
      // what: the bullets start their own lines, or the marker opens an HTML block that eats the `**`
      "rule-counts": [
        "",
        "",
        `- **${counts.core} rules** on plain TypeScript, **${counts.react}** with React, **${counts.reactNative}** on React Native, ${counts.custom} of them custom-built`,
        `- library-specific rules ship only when you depend on that library: ${counts.detecting} self-detecting modules`,
      ].join("\n"),
      "opt-in": optIn,
    },
  ],
  [
    join(lintDir, "README.md"),
    {
      "rule-counts": `${counts.core} rules on plain TypeScript, ${counts.react} with React, ${counts.reactNative} on React Native, ${counts.custom} of them custom-built`,
      "opt-in": optIn,
    },
  ],
];

/** The file with `body` between `<!-- name -->` and its closer, or null when either marker is missing. */
const withRegion = (text: string, name: string, body: string): string | null => {
  const start = `<!-- ${name} -->`;
  const from = text.indexOf(start);
  const to = text.indexOf(`<!-- /${name} -->`, from);
  if (from === -1 || to === -1) return null;
  return text.slice(0, from + start.length) + body + text.slice(to);
};

validateRuleDocLinks(pages, lintDir);

/** A README with every generated region spliced back between its markers. */
const spliced = ([path, regions]: [string, Record<string, string>]): Generated => {
  let text = readFileSync(path, "utf8");
  for (const [name, body] of Object.entries(regions)) {
    const updated = withRegion(text, name, body);
    if (updated === null) throw new Error(`${path} lost its <!-- ${name} --> markers - put them back around it.`);
    text = updated;
  }
  return [path, text];
};

emit([...pages, ...readmeRegions.map(spliced)], "rule docs", "bun run docs:rules");
