// GENERATED by scripts/generate-rule-types.ts - do not edit by hand. `bun run types:rules` regenerates it.

import type { AllowWarnDeny } from "oxlint";

/** Every rule id `core()` adds on top of the entry below it. */
export type CoreRuleId =
  | "@ashstack/core/no-comments"
  | "@ashstack/core/no-naming-convention"
  | "@ashstack/core/no-packed-condition"
  | "@ashstack/core/use-design-system"
  | "@ashstack/core/components-tsx-only"
  | "@ashstack/core/hoist-intl"
  | "@ashstack/zod/prefer-enum";

declare module "oxlint" {
  interface DummyRuleMap {
    /**
     * Disallow every comment that is neither a `// what: <fact>` line, a `// why:` marker, nor a tooling directive. The message names the refactoring that removes it: Rename, Extract Function, Guard Clause. Surviving `// what:` lines are held to one short line each, at most `budget` per file (default 2); `escapeHatch: false` removes that hatch, so no discretionary prose survives. A `// why:` line is the marker `@ashstack/react-native/no-manual-memo` requires above a kept `memo`: held to the same one-line shape, never counted against `budget`, and kept even with `escapeHatch: false`, so the two rules run together. With `jsdoc: "allow"`, a `/** *\/` block documenting the declaration directly beneath it is kept, while a floating one still reports.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackcoreno-comments
     */
    "@ashstack/core/no-comments"?:
      | AllowWarnDeny
      | [AllowWarnDeny]
      | [AllowWarnDeny, { jsdoc?: "allow" | "report"; escapeHatch?: boolean; budget?: number }];
    /**
     * Require a variable, object property, type member or enum member to use one of the casings allowed for its kind.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackcoreno-naming-convention
     */
    "@ashstack/core/no-naming-convention"?: AllowWarnDeny | [AllowWarnDeny];
    /**
     * Require a condition to be split into named booleans once it holds too many boolean operators and comparisons. The option says how many, defaulting to 5.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackcoreno-packed-condition
     */
    "@ashstack/core/no-packed-condition"?: AllowWarnDeny | [AllowWarnDeny] | [AllowWarnDeny, number];
    /**
     * Disallow importing a raw primitive your design system already wraps. Wrapped components come from scanning the design-system directory, plus the explicit `use` map for names, paths and source modules the scan cannot infer. Files under the design-system directory (or `exempt`) are skipped.
     *
     * Off by default — opt in per project.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackcoreuse-design-system
     */
    "@ashstack/core/use-design-system"?:
      | AllowWarnDeny
      | [AllowWarnDeny]
      | [
          AllowWarnDeny,
          {
            dir?: string;
            alias?: string;
            use?: Record<
              string,
              | string
              | Array<string>
              | { replaces: string | Array<string>; from?: string; path?: string; reason?: string }
            >;
            exempt?: Array<string>;
          },
        ];
    /**
     * Require every file under the components directory to render JSX or be a re-export barrel. `dir` says which directory, defaulting to `src/components`.
     *
     * Off by default — opt in per project.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackcorecomponents-tsx-only
     */
    "@ashstack/core/components-tsx-only"?: AllowWarnDeny | [AllowWarnDeny] | [AllowWarnDeny, { dir?: string }];
    /**
     * Disallow `new Intl.*` inside a function that renders JSX, unless the call already sits in `useMemo` or `useCallback`.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackcorehoist-intl
     */
    "@ashstack/core/hoist-intl"?: AllowWarnDeny | [AllowWarnDeny];
    /**
     * Disallow `z.nativeEnum()` and any `z.union()` whose members are all `z.literal()` strings.
     *
     * @see https://github.com/AlshehriAli0/ashStack/blob/main/packages/lint/RULES.md#ashstackzodprefer-enum
     */
    "@ashstack/zod/prefer-enum"?: AllowWarnDeny | [AllowWarnDeny];
  }
}
